name: App Runner CI

on:
  push:
    branches:
      - master

  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_REPOSITORY: artist-info

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: setup sdk
        run: npm install aws-sdk

      - name: Check and create repo if needed
        id: create-ecr-repo
        uses: actions/github-script@v5
        with:
          script: require('./.github/workflows/ecr_setup.js')

      - name: Build, tag, and push image to Amazon ECR
        id: push-to-ecr
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:latest"

      - name: Check and create app runner if needed
        env:
          ECR_IMAGE_NAME: ${{ steps.push-to-ecr.outputs.image }}
        uses: actions/github-script@v5
        with:
          script: require('./.github/workflows/apprunner_setup.js')
